<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhRIyTi\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhRIyTi/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXhRIyTi.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXhRIyTi\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXhRIyTi\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XhRIyTi',
    'container.build_id' => '184d28d2',
    'container.build_time' => 1528426428,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhRIyTi');
